import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/header";
import {Footer} from "@/app/footer";

const FontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const FontMono = JetBrains_Mono({
  variable: "--font-jet-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FontSans.variable} ${FontMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
