import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const FontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const FontMono = JetBrains_Mono({
  variable: "--font-jet-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FontSans.variable} ${FontMono.variable}`}>
        <header className="border-b border-white">
          <nav>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/about/team">Team</Link>
            <Link href="/admin">Admin</Link>
            <Link href="/posts">Posts</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
